//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class atencionVehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public atencionVehiculo()
        {
            this.BoletaRevision = new HashSet<BoletaRevision>();
            this.CertificadoRevision = new HashSet<CertificadoRevision>();
            this.ResponsablePago = new HashSet<ResponsablePago>();
            this.ResultadoEstacionGases = new HashSet<ResultadoEstacionGases>();
            this.ResultadosEstacionFrenometro = new HashSet<ResultadosEstacionFrenometro>();
            this.ResultadosEstacionVisuales = new HashSet<ResultadosEstacionVisuales>();
            this.TrazaWebServiceMTT = new HashSet<TrazaWebServiceMTT>();
        }
    
        public int id { get; set; }
        public int propietarioId { get; set; }
        public int vehiculoTipoId { get; set; }
        public string PatenteVehiculo { get; set; }
        public int SelloId { get; set; }
        public int marcaId { get; set; }
        public int modeloId { get; set; }
        public int año { get; set; }
        public int cilindradaVehiculo { get; set; }
        public int nroMotor { get; set; }
        public string nroChasis { get; set; }
        public int nroPuertas { get; set; }
        public int transmisionId { get; set; }
        public int combustibleId { get; set; }
        public int traccionId { get; set; }
        public int servicioId { get; set; }
    
        public virtual MarcaVehiculo MarcaVehiculo { get; set; }
        public virtual ModeloVehiculo ModeloVehiculo { get; set; }
        public virtual PropietarioVehiculo PropietarioVehiculo { get; set; }
        public virtual SelloVehiculo SelloVehiculo { get; set; }
        public virtual Servicios Servicios { get; set; }
        public virtual TipoCombustible TipoCombustible { get; set; }
        public virtual TipoVehiculo TipoVehiculo { get; set; }
        public virtual Traccion Traccion { get; set; }
        public virtual Transmision Transmision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoletaRevision> BoletaRevision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificadoRevision> CertificadoRevision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponsablePago> ResponsablePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadoEstacionGases> ResultadoEstacionGases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadosEstacionFrenometro> ResultadosEstacionFrenometro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadosEstacionVisuales> ResultadosEstacionVisuales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrazaWebServiceMTT> TrazaWebServiceMTT { get; set; }
    }
}
