//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoletaRevision
    {
        public int id { get; set; }
        public int nroAtencionId { get; set; }
        public int SucursalId { get; set; }
        public string vehiculoPatente { get; set; }
        public int formaPagoId { get; set; }
        public int ServicioId { get; set; }
    
        public virtual atencionVehiculo atencionVehiculo { get; set; }
        public virtual Servicios Servicios { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoPagos TipoPagos { get; set; }
    }
}
