//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IdiaEntities : DbContext
    {
        public IdiaEntities()
            : base("name=IdiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<atencionVehiculo> atencionVehiculo { get; set; }
        public virtual DbSet<BoletaRevision> BoletaRevision { get; set; }
        public virtual DbSet<CertificadoRevision> CertificadoRevision { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<EstadoRevision> EstadoRevision { get; set; }
        public virtual DbSet<Jefatura> Jefatura { get; set; }
        public virtual DbSet<MarcaVehiculo> MarcaVehiculo { get; set; }
        public virtual DbSet<ModeloVehiculo> ModeloVehiculo { get; set; }
        public virtual DbSet<Perfiles> Perfiles { get; set; }
        public virtual DbSet<PropietarioVehiculo> PropietarioVehiculo { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<ResponsablePago> ResponsablePago { get; set; }
        public virtual DbSet<ResultadoEstacionGases> ResultadoEstacionGases { get; set; }
        public virtual DbSet<ResultadosEstacionFrenometro> ResultadosEstacionFrenometro { get; set; }
        public virtual DbSet<ResultadosEstacionVisuales> ResultadosEstacionVisuales { get; set; }
        public virtual DbSet<SelloVehiculo> SelloVehiculo { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<TipoCombustible> TipoCombustible { get; set; }
        public virtual DbSet<TipoPagos> TipoPagos { get; set; }
        public virtual DbSet<TipoVehiculo> TipoVehiculo { get; set; }
        public virtual DbSet<Traccion> Traccion { get; set; }
        public virtual DbSet<Transmision> Transmision { get; set; }
        public virtual DbSet<TrazaWebServiceMTT> TrazaWebServiceMTT { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
