//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponsablePago
    {
        public int id { get; set; }
        public int NroAtencionId { get; set; }
        public string rutCliente { get; set; }
        public string clienteNombres { get; set; }
        public string clienteApellidoPaterno { get; set; }
        public string cleinteApellidoMaterno { get; set; }
        public int telefono { get; set; }
        public string email { get; set; }
        public string dirección { get; set; }
    
        public virtual atencionVehiculo atencionVehiculo { get; set; }
    }
}
