//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadosEstacionVisuales
    {
        public int id { get; set; }
        public int nroAtencionId { get; set; }
        public string vehiculoPatente { get; set; }
        public string comprobacionNroMotor { get; set; }
        public string comprobacionNroChazis { get; set; }
        public string estadoLuzFreno { get; set; }
        public string estadoTercerLuzFreno { get; set; }
        public string estadoLuzVirage { get; set; }
        public string estadoLuzReversa { get; set; }
    
        public virtual atencionVehiculo atencionVehiculo { get; set; }
    }
}
