//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadosEstacionFrenometro
    {
        public int id { get; set; }
        public int nroAtencionId { get; set; }
        public string vechiculoPatente { get; set; }
        public int resultadoAlineacion { get; set; }
        public int resultadoSuspencion { get; set; }
        public int resultadoFrenoIzquierdo { get; set; }
        public int resultadoFrenoDerecho { get; set; }
        public int resultadoFrenoEmergencia { get; set; }
        public int resultadoLucesAltas { get; set; }
        public int resultadoLucesBajas { get; set; }
    
        public virtual atencionVehiculo atencionVehiculo { get; set; }
    }
}
