//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrazaWebServiceMTT
    {
        public int id { get; set; }
        public int nroAtencionId { get; set; }
        public string respuestaWebService { get; set; }
        public System.DateTime fechaHoraRespuesta { get; set; }
    
        public virtual atencionVehiculo atencionVehiculo { get; set; }
    }
}
