//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id { get; set; }
        public string nombreUsuario { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string mail { get; set; }
        public int ciudadId { get; set; }
        public int perfilId { get; set; }
        public int jefaturaId { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Jefatura Jefatura { get; set; }
        public virtual Perfiles Perfiles { get; set; }
    }
}
